---
- name: Edge health check usecase
  hosts: node1
  vars_files:
      - vars/main.yaml
  roles:
    - health_check_interface_packet_drop
    - health_check_copp_packet_drop
    - health_check_rate_limit_packet_drop
    - health_check_mac_address
    - health_check_ping
    - health_check_memory
    - health_check_bgp_summary
