- name: Parse show ip bgp summary
  ansible.utils.cli_parse: 
    command: "show ip bgp summary"
    parser: 
      name: ansible.netcommon.native
    set_fact: bgp_summary 

- debug:
    var: bgp_summary

- name: Loop through bgp summary to check for neighbor
  set_fact:
    neighbor_present: "yes"
  when: (health_check.bgp_neighbor == item.value['neighbor']) and  (item.value['state'] == 'up')
  loop: "{{ bgp_summary | dict2items }}"

- name: Check if the given neighbor is present
  assert:
    that:
      - neighbor_present is defined
    fail_msg: >
      "{{ health_check.bgp_neighbor }}" is not present/up
